### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by luizs81** [bakercp/ofxPS3EyeGrabber#4]
Hi, 
I'm trying to use this addon on my OF project (on Windows) but I'm getting many errors on compiling time in the ps3eye.cpp file. The debug function isn't identified as well as many others related to libusb library. But yes, I also included the ofxKinect addon and also included the reference for ofxKinect.h. 

Any idea if it should work on Windows and/or Visual Studio projects? 
Thanks in advance

**Comment by blazm** [comment]
Hello, 
I managed to build this addon under windows. Instead of using libusb from ofxKinect, I only used original libusb (.lib + .h) from @inspirit (https://github.com/inspirit/PS3EYEDriver). This removes nearly all of the errors. Since I'm using oF 0.8.1 a few things needed some simple fixes, but overall I should say that it works pretty good.

![multiple_ps3_eyes](https://cloud.githubusercontent.com/assets/3786148/9254253/cdbfb872-41e2-11e5-9e1b-230a32ca2285.PNG)

**Comment by bakercp** [comment]
@blazm thanks for the feedback!

**Comment by princemio** [comment]
hmm . didnt got it working. I mean of course killing all the debug consoles...but there was some errors still from libusb and usbmanager - that i did not understand. anyone wants to share some thoughts how to get this working? would be really cool !!

**Comment by morphogencc** [comment]
Hey all -- I'm trying to get this working, and created a branch in my own repository:

https://github.com/morphogencc/ofxPS3EyeGrabber/tree/feature-windows_fix

It has a Visual Studio project in example-windows that I'm using for testing.  I've added `libusb-1.0` to the repository and link to it directly to avoid some of the earlier issues.  The following issues are:

* Missing `getopt.h`.  This looks like it might be a linux library?  I'm not sure.
* Issues with `std::min`; this is a pretty standard library conflict issue and I should be able to resolve it.
* issues with the return types in `ofxPS3EyeGrabber.h`; I imagine these are related to the new oF version (0.9.1).

If people want to try to help me resolve this, we can have a working windows version soon :)

**Comment by morphogencc** [comment]
Oh, hey -- using the dynamically linked version of the library fixed this.

Now I need to dig up my PS3 Eye and see if this works, now that I know it compiles just fine :)

**Comment by morphogencc** [comment]
@blazm Could you share a fork of the code with your changes?  It'd be great to have a working version :)

**Comment by blazm** [comment]
Sure, I just uploaded the changes recently. Here: https://github.com/blazm/ofxPS3EyeGrabber

Please take a look at example_PS3_multicam and let me know if it still works (it's been some time since I made the changes).

**Comment by morphogencc** [comment]
@blazm I just loaded it up and it doesn't seem to work -- it's missing the .dll or .lib file for libusb, and it's not compatible with the of v0.9 base classes.  I tidied it up a bit, but I get the same errors as I posted in my branch.

I don't understand `libusb` very well, but it seems like something isn't configured quite right in the guts (either for of v0.9 or windows 7), and it's returning a libusb error when it tries to open up the device.

@bakercp -- are you more familiar with how libusb works?

**Comment by blazm** [comment]
Yeah, I just uploaded it, as it was... I did not check if it works or not... It worked before, but I'm not sure what could be the issue. Will take a look at it, when I'll have more time...

However, I found out, that I did not upload **libusb-1.0.lib** file before (.gitignore was ignoring it). So I pushed it just now (check last commit). Please include it in project settings and try again. Hopefully, now there won't be any more errors regarding libusb.

**Comment by blazm** [comment]
I'm adding two screenshots from my configuration (which works). So check if you configured everything  (source files and libusb-1.0.lib) as it should be:

![project_ofx_include_files_1](https://cloud.githubusercontent.com/assets/3786148/13900442/a5ed1170-ee06-11e5-876e-8c97717d4045.png)
![project_ofx_include_files](https://cloud.githubusercontent.com/assets/3786148/13900443/a5eec6f0-ee06-11e5-8289-dd9c71fae857.png)

**Comment by morphogencc** [comment]
Hmm, have you tested it with of v0.9.1?  It doesn't seem to be compatible with its inherited base classes out of the box, and there's some linker issues.  I'll see if I can get it to work.

**Comment by blazm** [comment]
I did not test it on 0.9.1 yet. It should work on 0.8.1 (which I'm currently using). Did you solve the problems with **libusb**?

**Comment by morphogencc** [comment]
Unfortunately not; I had to make some minor changes to your ofxPS3Eye class to make it compatible with the new inherited class, but it still won't compile.

I get linker errors:

```
Error	LNK2001	unresolved external symbol ___iob_func	PS3_advanced_multicam	..\..\..\addons\ofxPS3EyeGrabber\example_PS3_multicam\libusb-1.0.lib(core.obj)	1	
Error	LNK1120	1 unresolved externals	PS3_advanced_multicam	..\..\..\addons\ofxPS3EyeGrabber\example_PS3_multicam\bin\PS3_advanced_multicam_debug.exe	1	
```

**Comment by bluelemonade** [comment]
hello,

how can I fix my compiling error. which VS version an OF version, which tree of the Plugin should I use?

reagards

**Comment by blazm** [comment]
Hi,

@morphogencc - I think your project is missing configuration path for: libusb-1.0.lib
Please check if directory **..\..\..\addons\ofxPS3EyeGrabber\libs\libusb-1.0\vc10** is included under Configuration Properties -> Linker -> General -> Additional Library Include directories

@bluelemonade - Apparently you are using the version with Linux based code in it. Check out this repo: https://github.com/blazm/ofxPS3EyeGrabber - master branch (this one uses oF 0.8.1 and VS 2012).

**Comment by bluelemonade** [comment]
hello,

I am using the multicam project with VS2012 express. i switch the toolset to v110. v120 is not included in the express version. its part of vs2013)

error LNK1104: Datei "./bin/libusb-1.0.lib" kann nicht geöffnet werden.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\LINK	PS3_advanced_multicam

ok, I copied the lib to the bin folder...   and compiled new:

I got this:
Fehler	25	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofAppRunner.obj)	PS3_advanced_multicam
Fehler	26	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofLog.obj)	PS3_advanced_multicam
Fehler	27	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofThread.obj)	PS3_advanced_multicam
Fehler	28	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofTexture.obj)	PS3_advanced_multicam
Fehler	29	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofGraphics.obj)	PS3_advanced_multicam
Fehler	30	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofEvents.obj)	PS3_advanced_multicam
Fehler	31	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofColor.obj)	PS3_advanced_multicam
Fehler	32	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofPixels.obj)	PS3_advanced_multicam
Fehler	33	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofMath.obj)	PS3_advanced_multicam
Fehler	34	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofRectangle.obj)	PS3_advanced_multicam
Fehler	35	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofUtils.obj)	PS3_advanced_multicam
Fehler	36	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofGLUtils.obj)	PS3_advanced_multicam
Fehler	37	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofSoundPlayer.obj)	PS3_advanced_multicam
Fehler	38	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofImage.obj)	PS3_advanced_multicam
Fehler	39	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofGLRenderer.obj)	PS3_advanced_multicam
Fehler	40	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofGLProgrammableRenderer.obj)	PS3_advanced_multicam
Fehler	41	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofTrueTypeFont.obj)	PS3_advanced_multicam
Fehler	42	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofURLFileLoader.obj)	PS3_advanced_multicam
Fehler	43	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofQtUtils.obj)	PS3_advanced_multicam
Fehler	44	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofAppGLFWWindow.obj)	PS3_advanced_multicam
Fehler	45	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofFileUtils.obj)	PS3_advanced_multicam
Fehler	46	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofMesh.obj)	PS3_advanced_multicam
Fehler	47	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofMatrix4x4.obj)	PS3_advanced_multicam
Fehler	48	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofVboMesh.obj)	PS3_advanced_multicam
Fehler	49	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofPath.obj)	PS3_advanced_multicam
Fehler	50	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofCairoRenderer.obj)	PS3_advanced_multicam
Fehler	51	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofRendererCollection.obj)	PS3_advanced_multicam
Fehler	52	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofPolyline.obj)	PS3_advanced_multicam
Fehler	53	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofFmodSoundPlayer.obj)	PS3_advanced_multicam
Fehler	54	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofMatrixStack.obj)	PS3_advanced_multicam
Fehler	55	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(of3dPrimitives.obj)	PS3_advanced_multicam
Fehler	56	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofBitmapFont.obj)	PS3_advanced_multicam
Fehler	57	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofShader.obj)	PS3_advanced_multicam
Fehler	58	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofVec4f.obj)	PS3_advanced_multicam
Fehler	59	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofQuaternion.obj)	PS3_advanced_multicam
Fehler	60	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofTessellator.obj)	PS3_advanced_multicam
Fehler	61	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(of3dUtils.obj)	PS3_advanced_multicam
Fehler	62	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofNode.obj)	PS3_advanced_multicam
Fehler	63	error LNK2038: Konflikt ermittelt f³r "_MSC_VER": Der Wert "1800" stimmt nicht mit dem Wert "1700" in main.obj ³berein.	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(of3dGraphics.obj)	PS3_advanced_multicam
Fehler	64	error LNK2001: Nicht aufgel÷stes externes Symbol "__dtoui3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofEvents.obj)	PS3_advanced_multicam
Fehler	65	error LNK2001: Nicht aufgel÷stes externes Symbol "__dtoul3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofEvents.obj)	PS3_advanced_multicam
Fehler	66	error LNK2001: Nicht aufgel÷stes externes Symbol "__ultod3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofEvents.obj)	PS3_advanced_multicam
Fehler	67	error LNK2001: Nicht aufgel÷stes externes Symbol "__ultod3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofUtils.obj)	PS3_advanced_multicam
Fehler	68	error LNK2001: Nicht aufgel÷stes externes Symbol "__ftoui3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofColor.obj)	PS3_advanced_multicam
Fehler	69	error LNK2001: Nicht aufgel÷stes externes Symbol "__ftoui3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofPixels.obj)	PS3_advanced_multicam
Fehler	70	error LNK2001: Nicht aufgel÷stes externes Symbol "__ftoui3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofCairoRenderer.obj)	PS3_advanced_multicam
Fehler	71	error LNK2001: Nicht aufgel÷stes externes Symbol "__ltod3".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofQtUtils.obj)	PS3_advanced_multicam
Fehler	72	error LNK2001: Nicht aufgel÷stes externes Symbol ""__declspec(dllimport) public: __thiscall std::ios_base::operator bool(void)const " (__imp_??Bios_base@std@@QBE_NXZ)".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofFileUtils.obj)	PS3_advanced_multicam
Fehler	73	error LNK2001: Nicht aufgel÷stes externes Symbol ""__declspec(dllimport) public: __thiscall std::ios_base::operator bool(void)const " (__imp_??Bios_base@std@@QBE_NXZ)".	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\openframeworksLib_debug.lib(ofShader.obj)	PS3_advanced_multicam
Fehler	74	error LNK1120: 6 nicht aufgel÷ste Externe	E:\of_v0.8.1_vs_release\addons\ofxPS3EyeGrabber\example_PS3_multicam\bin\PS3_advanced_multicam_debug.exe	PS3_advanced_multicam

**Comment by blazm** [comment]
No problem. I'm glad that it works. 

At the moment I'm still using VS2012 and oF 0.8.1. Maybe I'll port it to oF 0.9.1 / VS2015 in the future.

**Comment by xseignard** [comment]
Hello

Any updates here? I'm trying to use this addon on win8.1 with oF 0.9.7 (msys2 release) with no luck

I tried with linux and it's OK. 

With this addon (or the forked one at @blazm repo) it cannot compile.

Regards

**Comment by bakercp** [comment]
Master branch w/ oF master on windows should now be working according to CI.  Closing this. Please reopen if it doesn't work.

**Comment by moebiussurfing** [comment]
Anybody got it working these days?

I am on VS2017, Windows10 with CL_Eye drivers installed and camera working, master branch in OF and in the addon too. 
Used PG straightforward to create the project (ofxKinect, ofxOpenCv) ...

```
1>------ Build started: Project: example_simple, Configuration: Release x64 ------
1>   Creating library bin\example_simple.lib and object bin\example_simple.exp
1>tilt.obj : error LNK2001: unresolved external symbol libusb_error_name
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_error_name
1>ofxPS3EyeGrabber.obj : error LNK2001: unresolved external symbol libusb_error_name
1>tilt.obj : error LNK2001: unresolved external symbol libusb_bulk_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_bulk_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_init
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_init
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_exit
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_exit
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_device_list
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_get_device_list
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_free_device_list
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_free_device_list
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_device_descriptor
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_get_device_descriptor
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_active_config_descriptor
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_get_active_config_descriptor
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_free_config_descriptor
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_free_config_descriptor
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_bus_number
1>ofxPS3EyeGrabber.obj : error LNK2001: unresolved external symbol libusb_get_bus_number
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_get_bus_number
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_parent
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_max_iso_packet_size
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_open
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_open
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_close
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_close
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_device
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_get_device
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_claim_interface
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_claim_interface
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_release_interface
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_release_interface
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_set_interface_alt_setting
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_reset_device
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_alloc_transfer
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_alloc_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_submit_transfer
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_submit_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_cancel_transfer
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_cancel_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_free_transfer
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_free_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_control_transfer
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_control_transfer
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_get_string_descriptor_ascii
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_handle_events_timeout
1>usb_libusb10.obj : error LNK2001: unresolved external symbol libusb_handle_events
1>ofxPS3EyeGrabber.obj : error LNK2001: unresolved external symbol libusb_get_port_numbers
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_get_port_numbers
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_set_debug
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_ref_device
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_unref_device
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_clear_halt
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_set_auto_detach_kernel_driver
1>ps3eye.obj : error LNK2001: unresolved external symbol libusb_handle_events_timeout_completed
1>bin\example_simple.exe : fatal error LNK1120: 34 unresolved externals
1>Done building project "example_simple.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

```

**Comment by PhuDoTuong** [comment]
@blazm, I used your **example_PS3_multicam** project. I work fine, but I got 3 devices (actually was 2 devices). I try to use following code in "main.cpp":
#include "ofApp.h"
#include "ps3eye.h"

int main()
{
	std::vector<ps3eye::PS3EYECam::PS3EYERef> devices(ps3eye::PS3EYECam::getDevices());
	std::cout << devices.size() << "\n";
    ofSetupOpenGL(320 * 3, 240, OF_WINDOW);
    ofRunApp(new ofApp());

}
The result in openFramework GUI:
![image](https://user-images.githubusercontent.com/73333393/103395300-34389880-4b60-11eb-9bfe-86c016d62012.png)
But when I use these code in @inspirit project (SDL2 example) the results is 2 devices:
int main(int argc, char *argv[])
{
	std::vector<ps3eye::PS3EYECam::PS3EYERef> devices(ps3eye::PS3EYECam::getDevices());
	std::cout << devices.size() << "\n";
	system("pause");
	return 0;
}
